# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache CPAN
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.cpan
        key: ${{ runner.os }}-${{ hashFiles('**/cpanfile') }}

    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1.6.0
      with:
        perl-version: 5.32.0
        distribution: "default"
        
    - name: Update CPAN
      run: cpan install CPAN && cpan CPAN::DistnameInfo

    - name: Run tests
      run: cpan Module::Install Module::Find Class::Load Text::MicroTemplate::File AnyEvent::Fork AnyEvent::HTTP Plack::Builder Plack::Handler::Twiggy
